-- Doplnění 2. a 6. pádu (detail.genitive „do Norska", detail.locative „v Norsku") u míst,
-- která je po migraci neměla (456 z 669 publikovaných míst k 4. 9. 2026). Pády používají
-- SEO šablony (src/lib/seo-templates.ts): titulky cílů „Název v Městě", popisky, „Vstupní
-- podmínky a víza do …". Tvary navrhl AI asistent (kolísající jména podle Internetové jazykové příručky), uživatel seznam schválil.
-- Idempotentní: zapisuje jen tam, kde je pole prázdné; původní hodnoty do zaloha.pages_pady_2026_09_04.
-- Spuštění (dev):  docker compose exec -T postgres psql -U postgres -d aracze < scripts/seo-fill-place-cases.sql
-- Prod: stejně proti produkční DB (služba `postgres`), potom `docker compose up -d --force-recreate cms`.
BEGIN;
CREATE SCHEMA IF NOT EXISTS zaloha;
CREATE TEMP TABLE pady (slug text PRIMARY KEY, gen text NOT NULL, loc text NOT NULL);
INSERT INTO pady (slug, gen, loc) VALUES
  ($q$/afrika$q$, $q$do Afriky$q$, $q$v Africe$q$),
  ($q$/amerika$q$, $q$do Ameriky$q$, $q$v Americe$q$),
  ($q$/asie$q$, $q$do Asie$q$, $q$v Asii$q$),
  ($q$/australie$q$, $q$do Austrálie$q$, $q$v Austrálii$q$),
  ($q$/evropa$q$, $q$do Evropy$q$, $q$v Evropě$q$),
  ($q$/anglie/cambridge$q$, $q$do Cambridge$q$, $q$v Cambridgi$q$),
  ($q$/anglie/lancaster$q$, $q$do Lancasteru$q$, $q$v Lancasteru$q$),
  ($q$/anglie/oxford$q$, $q$do Oxfordu$q$, $q$v Oxfordu$q$),
  ($q$/anglie/st-albans$q$, $q$do St. Albans$q$, $q$v St. Albans$q$),
  ($q$/anglie/stratford-upon-avon$q$, $q$do Stratfordu upon Avon$q$, $q$ve Stratfordu upon Avon$q$),
  ($q$/anglie/windsor$q$, $q$do Windsoru$q$, $q$ve Windsoru$q$),
  ($q$/argentina/el-calafate$q$, $q$do El Calafate$q$, $q$v El Calafate$q$),
  ($q$/argentina/mendoza$q$, $q$do Mendozy$q$, $q$v Mendoze$q$),
  ($q$/argentina/mendoza-provincie$q$, $q$do provincie Mendoza$q$, $q$v provincii Mendoza$q$),
  ($q$/argentina/narodni-park-iguazu$q$, $q$do národního parku Iguazú$q$, $q$v národním parku Iguazú$q$),
  ($q$/argentina/san-carlos-de-bariloche$q$, $q$do San Carlos de Bariloche$q$, $q$v San Carlos de Bariloche$q$),
  ($q$/argentina/ushuaia$q$, $q$do Ushuaie$q$, $q$v Ushuaii$q$),
  ($q$/belgie/gent$q$, $q$do Gentu$q$, $q$v Gentu$q$),
  ($q$/belgie/waterloo$q$, $q$do Waterloo$q$, $q$ve Waterloo$q$),
  ($q$/belorusko/turov$q$, $q$do Turova$q$, $q$v Turově$q$),
  ($q$/belorusko/vitebsk$q$, $q$do Vitebsku$q$, $q$ve Vitebsku$q$),
  ($q$/bosna-a-hercegovina/biha$q$, $q$do Bihaće$q$, $q$v Bihaći$q$),
  ($q$/bosna-a-hercegovina/jajce$q$, $q$do Jajce$q$, $q$v Jajci$q$),
  ($q$/brazilie/brasilia$q$, $q$do Brasilie$q$, $q$v Brasilii$q$),
  ($q$/brazilie/foz-do-iguazu$q$, $q$do Foz do Iguazú$q$, $q$ve Foz do Iguazú$q$),
  ($q$/brazilie/ouro-preto$q$, $q$do Ouro Preto$q$, $q$v Ouro Preto$q$),
  ($q$/brazilie/paraty$q$, $q$do Paraty$q$, $q$v Paraty$q$),
  ($q$/brazilie/sao-paulo$q$, $q$do Sao Paula$q$, $q$v Sao Paulu$q$),
  ($q$/bulharsko/burgas$q$, $q$do Burgasu$q$, $q$v Burgasu$q$),
  ($q$/bulharsko/melnik$q$, $q$do Melniku$q$, $q$v Melniku$q$),
  ($q$/bulharsko/nesebar$q$, $q$do Nesebaru$q$, $q$v Nesebaru$q$),
  ($q$/bulharsko/plovdiv$q$, $q$do Plovdivu$q$, $q$v Plovdivu$q$),
  ($q$/bulharsko/sandanski$q$, $q$do Sandanski$q$, $q$v Sandanski$q$),
  ($q$/bulharsko/svaty-konstantin-a-helena$q$, $q$do Svatého Konstantina a Heleny$q$, $q$ve Svatém Konstantinu a Heleně$q$),
  ($q$/cerna-hora/budva$q$, $q$do Budvy$q$, $q$v Budvě$q$),
  ($q$/cerna-hora/cetinje$q$, $q$do Cetinje$q$, $q$v Cetinji$q$),
  ($q$/cerna-hora/herceg-novi$q$, $q$do Herceg Novi$q$, $q$v Herceg Novi$q$),
  ($q$/cerna-hora/kotor$q$, $q$do Kotoru$q$, $q$v Kotoru$q$),
  ($q$/cerna-hora/narodni-park-durmitor$q$, $q$do národního parku Durmitor$q$, $q$v národním parku Durmitor$q$),
  ($q$/ceska-republika/adrspassko-teplicke-skaly$q$, $q$do Adršpašsko-teplických skal$q$, $q$v Adršpašsko-teplických skalách$q$),
  ($q$/ceska-republika/blansko$q$, $q$do Blanska$q$, $q$v Blansku$q$),
  ($q$/ceska-republika/brno$q$, $q$do Brna$q$, $q$v Brně$q$),
  ($q$/ceska-republika/broumov$q$, $q$do Broumova$q$, $q$v Broumově$q$),
  ($q$/ceska-republika/broumovsko$q$, $q$na Broumovsko$q$, $q$na Broumovsku$q$),
  ($q$/ceska-republika/ceske-svycarsko$q$, $q$do Českého Švýcarska$q$, $q$v Českém Švýcarsku$q$),
  ($q$/ceska-republika/cesky-krumlov$q$, $q$do Českého Krumlova$q$, $q$v Českém Krumlově$q$),
  ($q$/ceska-republika/cesky-raj$q$, $q$do Českého ráje$q$, $q$v Českém ráji$q$),
  ($q$/ceska-republika/hradec-kralove$q$, $q$do Hradce Králové$q$, $q$v Hradci Králové$q$),
  ($q$/ceska-republika/hrensko$q$, $q$do Hřenska$q$, $q$v Hřensku$q$),
  ($q$/ceska-republika/hronov$q$, $q$do Hronova$q$, $q$v Hronově$q$),
  ($q$/ceska-republika/javori-hory$q$, $q$do Javořích hor$q$, $q$v Javořích horách$q$),
  ($q$/ceska-republika/jeseniky$q$, $q$do Jeseníků$q$, $q$v Jeseníkách$q$),
  ($q$/ceska-republika/jetrichovice-a-okolni-vyhlidky$q$, $q$do Jetřichovic a okolí$q$, $q$v Jetřichovicích a okolí$q$),
  ($q$/ceska-republika/jicin$q$, $q$do Jičína$q$, $q$v Jičíně$q$),
  ($q$/ceska-republika/jizni-cechy$q$, $q$do jižních Čech$q$, $q$v jižních Čechách$q$),
  ($q$/ceska-republika/karlovy-vary$q$, $q$do Karlových Varů$q$, $q$v Karlových Varech$q$),
  ($q$/ceska-republika/kutna-hora$q$, $q$do Kutné Hory$q$, $q$v Kutné Hoře$q$),
  ($q$/ceska-republika/litomerice$q$, $q$do Litoměřic$q$, $q$v Litoměřicích$q$),
  ($q$/ceska-republika/litomysl$q$, $q$do Litomyšle$q$, $q$v Litomyšli$q$),
  ($q$/ceska-republika/moravsky-kras$q$, $q$do Moravského krasu$q$, $q$v Moravském krasu$q$),
  ($q$/ceska-republika/olomouc$q$, $q$do Olomouce$q$, $q$v Olomouci$q$),
  ($q$/ceska-republika/ostrava$q$, $q$do Ostravy$q$, $q$v Ostravě$q$),
  ($q$/ceska-republika/pardubice$q$, $q$do Pardubic$q$, $q$v Pardubicích$q$),
  ($q$/ceska-republika/plzen$q$, $q$do Plzně$q$, $q$v Plzni$q$),
  ($q$/ceska-republika/podripsko$q$, $q$na Podřipsko$q$, $q$na Podřipsku$q$),
  ($q$/ceska-republika/police-nad-metuji$q$, $q$do Police nad Metují$q$, $q$v Polici nad Metují$q$),
  ($q$/ceska-republika/praha$q$, $q$do Prahy$q$, $q$v Praze$q$),
  ($q$/ceska-republika/roudnice-nad-labem$q$, $q$do Roudnice nad Labem$q$, $q$v Roudnici nad Labem$q$),
  ($q$/ceska-republika/sobotka$q$, $q$do Sobotky$q$, $q$v Sobotce$q$),
  ($q$/ceska-republika/soutesky-kamenice$q$, $q$do soutěsek Kamenice$q$, $q$v soutěskách Kamenice$q$),
  ($q$/ceska-republika/sumava$q$, $q$na Šumavu$q$, $q$na Šumavě$q$),
  ($q$/ceska-republika/teplice-nad-metuji$q$, $q$do Teplic nad Metují$q$, $q$v Teplicích nad Metují$q$),
  ($q$/ceska-republika/trebic$q$, $q$do Třebíče$q$, $q$v Třebíči$q$),
  ($q$/chorvatsko/dakovo$q$, $q$do Dakova$q$, $q$v Dakovu$q$),
  ($q$/chorvatsko/istrie$q$, $q$na Istrii$q$, $q$na Istrii$q$),
  ($q$/chorvatsko/marija-bistrica$q$, $q$do Marije Bistrice$q$, $q$v Mariji Bistrici$q$),
  ($q$/chorvatsko/mesto-korcula$q$, $q$do města Korčula$q$, $q$ve městě Korčula$q$),
  ($q$/chorvatsko/mesto-pag$q$, $q$do města Pag$q$, $q$ve městě Pag$q$),
  ($q$/chorvatsko/narodni-park-krka$q$, $q$do národního parku Krka$q$, $q$v národním parku Krka$q$),
  ($q$/chorvatsko/narodni-park-paklenica$q$, $q$do národního parku Paklenica$q$, $q$v národním parku Paklenica$q$),
  ($q$/chorvatsko/narodni-park-severni-velebit$q$, $q$do národního parku Severní Velebit$q$, $q$v národním parku Severní Velebit$q$),
  ($q$/chorvatsko/novigrad$q$, $q$do Novigradu$q$, $q$v Novigradu$q$),
  ($q$/chorvatsko/osijek$q$, $q$do Osijeku$q$, $q$v Osijeku$q$),
  ($q$/chorvatsko/ostrov-cres/beli$q$, $q$do Beli$q$, $q$v Beli$q$),
  ($q$/chorvatsko/ostrov-cres/osor$q$, $q$do Osoru$q$, $q$v Osoru$q$),
  ($q$/chorvatsko/ostrov-cres/valun$q$, $q$do Valunu$q$, $q$ve Valunu$q$),
  ($q$/chorvatsko/ostrov-korcula$q$, $q$na ostrov Korčula$q$, $q$na ostrově Korčula$q$),
  ($q$/chorvatsko/ostrov-krk/baska$q$, $q$do Bašky$q$, $q$v Bašce$q$),
  ($q$/chorvatsko/ostrov-krk/krk$q$, $q$do Krku$q$, $q$v Krku$q$),
  ($q$/chorvatsko/ostrov-krk/vrbnik$q$, $q$do Vrbniku$q$, $q$ve Vrbniku$q$),
  ($q$/chorvatsko/ostrov-lokrum$q$, $q$na ostrov Lokrum$q$, $q$na ostrově Lokrum$q$),
  ($q$/chorvatsko/ostrov-losinj/mali-losinj$q$, $q$do Malého Lošinje$q$, $q$v Malém Lošinji$q$),
  ($q$/chorvatsko/ostrov-losinj/veli-losinj$q$, $q$do Veli Lošinje$q$, $q$ve Veli Lošinji$q$),
  ($q$/chorvatsko/ostrov-rab/rab$q$, $q$do Rabu$q$, $q$v Rabu$q$),
  ($q$/chorvatsko/pazin$q$, $q$do Pazinu$q$, $q$v Pazinu$q$),
  ($q$/chorvatsko/plitvicka-jezera$q$, $q$na Plitvická jezera$q$, $q$na Plitvických jezerech$q$),
  ($q$/chorvatsko/porec$q$, $q$do Poreče$q$, $q$v Poreči$q$),
  ($q$/chorvatsko/prirodni-park-medvednica$q$, $q$do přírodního parku Medvednica$q$, $q$v přírodním parku Medvednica$q$),
  ($q$/chorvatsko/prirodni-park-velebit$q$, $q$do přírodního parku Velebit$q$, $q$v přírodním parku Velebit$q$),
  ($q$/chorvatsko/rovinj$q$, $q$do Rovinje$q$, $q$v Rovinji$q$),
  ($q$/chorvatsko/sibenik$q$, $q$do Šibeniku$q$, $q$v Šibeniku$q$),
  ($q$/chorvatsko/sisak$q$, $q$do Sisaku$q$, $q$v Sisaku$q$),
  ($q$/chorvatsko/varazdin$q$, $q$do Varaždinu$q$, $q$ve Varaždinu$q$),
  ($q$/cina/peking$q$, $q$do Pekingu$q$, $q$v Pekingu$q$),
  ($q$/cina/sanghaj$q$, $q$do Šanghaje$q$, $q$v Šanghaji$q$),
  ($q$/dansko/hillerd$q$, $q$do Hillerødu$q$, $q$v Hillerødu$q$),
  ($q$/dansko/ostrov-mon$q$, $q$na ostrov Mon$q$, $q$na ostrově Mon$q$),
  ($q$/egypt/doli-kralu$q$, $q$do Údolí králů$q$, $q$v Údolí králů$q$),
  ($q$/egypt/kahira$q$, $q$do Káhiry$q$, $q$v Káhiře$q$),
  ($q$/egypt/luxor$q$, $q$do Luxoru$q$, $q$v Luxoru$q$),
  ($q$/ekvador/otavalo$q$, $q$do Otavala$q$, $q$v Otavalu$q$),
  ($q$/estonsko/kunda$q$, $q$do Kundy$q$, $q$v Kundě$q$),
  ($q$/estonsko/tartu$q$, $q$do Tartu$q$, $q$v Tartu$q$),
  ($q$/francie/aix-en-provence$q$, $q$do Aix en Provence$q$, $q$v Aix en Provence$q$),
  ($q$/francie/arles$q$, $q$do Arles$q$, $q$v Arles$q$),
  ($q$/francie/avignon$q$, $q$do Avignonu$q$, $q$v Avignonu$q$),
  ($q$/francie/camargue$q$, $q$do Camargue$q$, $q$v Camargue$q$),
  ($q$/francie/carcassonne$q$, $q$do Carcassonne$q$, $q$v Carcassonne$q$),
  ($q$/francie/epernay$q$, $q$do Epernay$q$, $q$v Epernay$q$),
  ($q$/francie/montpellier$q$, $q$do Montpellieru$q$, $q$v Montpellieru$q$),
  ($q$/francie/saint-emilion$q$, $q$do Saint-Émilionu$q$, $q$v Saint-Émilionu$q$),
  ($q$/francie/saint-tropez$q$, $q$do Saint Tropez$q$, $q$v Saint Tropez$q$),
  ($q$/francie/toulouse$q$, $q$do Toulouse$q$, $q$v Toulouse$q$),
  ($q$/irsko/cobh$q$, $q$do Cobhu$q$, $q$v Cobhu$q$),
  ($q$/irsko/narodni-park-glenveagh$q$, $q$do národního parku Glenveagh$q$, $q$v národním parku Glenveagh$q$),
  ($q$/island/husavik$q$, $q$do Húsavíku$q$, $q$v Húsavíku$q$),
  ($q$/island/isafjrur$q$, $q$do Ísafjörðuru$q$, $q$v Ísafjörðuru$q$),
  ($q$/island/jihozapadni-island$q$, $q$na jihozápadní Island$q$, $q$na jihozápadním Islandu$q$),
  ($q$/island/narodni-park-ingvellir$q$, $q$do národního parku Þingvellir$q$, $q$v národním parku Þingvellir$q$),
  ($q$/island/narodni-park-jkulsargljufur$q$, $q$do národního parku Jökulsárgljúfur$q$, $q$v národním parku Jökulsárgljúfur$q$),
  ($q$/island/narodni-park-snfellsjkull$q$, $q$do národního parku Snæfellsjökull$q$, $q$v národním parku Snæfellsjökull$q$),
  ($q$/island/poloostrov-reykjanes$q$, $q$na poloostrov Reykjanes$q$, $q$na poloostrově Reykjanes$q$),
  ($q$/island/poloostrov-reykjanes/keflavik$q$, $q$do Keflavíku$q$, $q$v Keflavíku$q$),
  ($q$/island/snaefelsnes$q$, $q$na Snaefelsnes$q$, $q$na Snaefelsnesu$q$),
  ($q$/island/zapadni-fjordy$q$, $q$do Západních fjordů$q$, $q$v Západních fjordech$q$),
  ($q$/island/zapadni-pobrezi$q$, $q$na západní pobřeží$q$, $q$na západním pobřeží$q$),
  ($q$/italie/caorle$q$, $q$do Caorle$q$, $q$v Caorle$q$),
  ($q$/italie/neapol$q$, $q$do Neapole$q$, $q$v Neapoli$q$),
  ($q$/italie/sardinie/alghero$q$, $q$do Alghera$q$, $q$v Algheru$q$),
  ($q$/italie/sardinie/castelsardo$q$, $q$do Castelsarda$q$, $q$v Castelsardu$q$),
  ($q$/italie/sardinie/parco-naturale-regionale-di-porto-conte$q$, $q$do přírodního parku Porto Conte$q$, $q$v přírodním parku Porto Conte$q$),
  ($q$/italie/sicilie/agrigento$q$, $q$do Agrigenta$q$, $q$v Agrigentu$q$),
  ($q$/italie/sicilie/taormina$q$, $q$do Taorminy$q$, $q$v Taormině$q$),
  ($q$/italie/terst$q$, $q$do Terstu$q$, $q$v Terstu$q$),
  ($q$/italie/udine$q$, $q$do Udine$q$, $q$v Udine$q$),
  ($q$/italie/vatikan$q$, $q$do Vatikánu$q$, $q$ve Vatikánu$q$),
  ($q$/japonsko/kamakura$q$, $q$do Kamakury$q$, $q$v Kamakuře$q$),
  ($q$/japonsko/kobe$q$, $q$do Kóbe$q$, $q$v Kóbe$q$),
  ($q$/kapverdy/mindelo$q$, $q$do Mindela$q$, $q$v Mindelu$q$),
  ($q$/kapverdy/ostrov-boa-vista$q$, $q$na ostrov Boa Vista$q$, $q$na ostrově Boa Vista$q$),
  ($q$/kapverdy/ostrov-santo-antao$q$, $q$na ostrov Santo Antao$q$, $q$na ostrově Santo Antao$q$),
  ($q$/kapverdy/ostrov-sao-vicente$q$, $q$na ostrov Sao Vicente$q$, $q$na ostrově Sao Vicente$q$),
  ($q$/kazachstan/almaty$q$, $q$do Almaty$q$, $q$v Almaty$q$),
  ($q$/kazachstan/astana$q$, $q$do Astany$q$, $q$v Astaně$q$),
  ($q$/kazachstan/borodinovka$q$, $q$do Borodinovky$q$, $q$v Borodinovce$q$),
  ($q$/kazachstan/burabaj$q$, $q$do Burabaje$q$, $q$v Burabaji$q$),
  ($q$/kazachstan/carynsky-kanon$q$, $q$do Čarynského kaňonu$q$, $q$v Čarynském kaňonu$q$),
  ($q$/kazachstan/karaganda$q$, $q$do Karagandy$q$, $q$v Karagandě$q$),
  ($q$/kazachstan/sayram$q$, $q$do Sayramu$q$, $q$v Sayramu$q$),
  ($q$/kazachstan/symkent$q$, $q$do Šymkentu$q$, $q$v Šymkentu$q$),
  ($q$/kazachstan/taraz$q$, $q$do Tarazu$q$, $q$v Tarazu$q$),
  ($q$/kazachstan/turkestan$q$, $q$do Turkestánu$q$, $q$v Turkestánu$q$),
  ($q$/kypr/larnaka$q$, $q$do Larnaky$q$, $q$v Larnace$q$),
  ($q$/kyrgyzstan/biskek$q$, $q$do Biškeku$q$, $q$v Biškeku$q$),
  ($q$/kyrgyzstan/colpon-ata$q$, $q$do Čolpon Aty$q$, $q$v Čolpon Atě$q$),
  ($q$/lichtenstejnsko/schaan$q$, $q$do Schaanu$q$, $q$ve Schaanu$q$),
  ($q$/lichtenstejnsko/vaduz$q$, $q$do Vaduzu$q$, $q$ve Vaduzu$q$),
  ($q$/litva/siauliai$q$, $q$do Šiauliai$q$, $q$v Šiauliai$q$),
  ($q$/litva/smiltyne$q$, $q$do Smiltyné$q$, $q$ve Smiltyné$q$),
  ($q$/litva/trakai$q$, $q$do Trakai$q$, $q$v Trakai$q$),
  ($q$/lotyssko/cesis$q$, $q$do Cesisu$q$, $q$v Cesisu$q$),
  ($q$/lotyssko/jelgava$q$, $q$do Jelgavy$q$, $q$v Jelgavě$q$),
  ($q$/lotyssko/kolka$q$, $q$do Kolky$q$, $q$v Kolce$q$),
  ($q$/lotyssko/kuldiga$q$, $q$do Kuldigy$q$, $q$v Kuldize$q$),
  ($q$/lotyssko/sabile$q$, $q$do Sabile$q$, $q$v Sabile$q$),
  ($q$/lotyssko/sigulda$q$, $q$do Siguldy$q$, $q$v Siguldě$q$),
  ($q$/lotyssko/valmiera$q$, $q$do Valmiery$q$, $q$ve Valmieře$q$),
  ($q$/lucembursko/vianden$q$, $q$do Viandenu$q$, $q$ve Viandenu$q$),
  ($q$/madarsko/debrecen$q$, $q$do Debrecenu$q$, $q$v Debrecenu$q$),
  ($q$/madarsko/ostrihom$q$, $q$do Ostřihomi$q$, $q$v Ostřihomi$q$),
  ($q$/madarsko/pecs$q$, $q$do Pécse$q$, $q$v Pécsi$q$),
  ($q$/madarsko/villany$q$, $q$do Villány$q$, $q$ve Villány$q$),
  ($q$/makedonie/matka-canyon$q$, $q$do kaňonu Matka$q$, $q$v kaňonu Matka$q$),
  ($q$/makedonie/narodni-park-galicica$q$, $q$do národního parku Galičica$q$, $q$v národním parku Galičica$q$),
  ($q$/malta/gozo$q$, $q$na Gozo$q$, $q$na Gozu$q$),
  ($q$/malta/marsaxlokk$q$, $q$do Marsaxlokku$q$, $q$v Marsaxlokku$q$),
  ($q$/malta/mdina$q$, $q$do Mdiny$q$, $q$v Mdině$q$),
  ($q$/malta/mellieha$q$, $q$do Melliehy$q$, $q$v Melliehe$q$),
  ($q$/malta/mosta$q$, $q$do Mosty$q$, $q$v Mostě$q$),
  ($q$/malta/paola$q$, $q$do Paoly$q$, $q$v Paole$q$),
  ($q$/malta/rabat$q$, $q$do Rabatu$q$, $q$v Rabatu$q$),
  ($q$/malta/taqali$q$, $q$do Ta’Qali$q$, $q$v Ta’Qali$q$),
  ($q$/malta/victoria$q$, $q$do Victorie$q$, $q$ve Victorii$q$),
  ($q$/maroko/casablanca$q$, $q$do Casablanky$q$, $q$v Casablance$q$),
  ($q$/maroko/fez$q$, $q$do Fezu$q$, $q$ve Fezu$q$),
  ($q$/maroko/marrakes$q$, $q$do Marrakéše$q$, $q$v Marrakéši$q$),
  ($q$/maroko/rabat$q$, $q$do Rabatu$q$, $q$v Rabatu$q$),
  ($q$/myanmar/bagan$q$, $q$do Baganu$q$, $q$v Baganu$q$),
  ($q$/myanmar/kalaw$q$, $q$do Kalaw$q$, $q$v Kalaw$q$),
  ($q$/myanmar/mandalaj$q$, $q$do Mandalaje$q$, $q$v Mandalaji$q$),
  ($q$/myanmar/mingun$q$, $q$do Mingunu$q$, $q$v Mingunu$q$),
  ($q$/myanmar/rangun$q$, $q$do Rangúnu$q$, $q$v Rangúnu$q$),
  ($q$/nemecko/bamberk$q$, $q$do Bamberku$q$, $q$v Bamberku$q$),
  ($q$/nemecko/bernau-bei-berlin$q$, $q$do Bernau bei Berlin$q$, $q$v Bernau bei Berlin$q$),
  ($q$/nemecko/budysin$q$, $q$do Budyšína$q$, $q$v Budyšíně$q$),
  ($q$/nemecko/dessau-rolau$q$, $q$do Dessau-Roßlau$q$, $q$v Dessau-Roßlau$q$),
  ($q$/nemecko/hamburk$q$, $q$do Hamburku$q$, $q$v Hamburku$q$),
  ($q$/nemecko/kamenz$q$, $q$do Kamenzu$q$, $q$v Kamenzu$q$),
  ($q$/nemecko/konstanz$q$, $q$do Kostnice$q$, $q$v Kostnici$q$),
  ($q$/nemecko/lipsko$q$, $q$do Lipska$q$, $q$v Lipsku$q$),
  ($q$/nemecko/magdeburg$q$, $q$do Magdeburgu$q$, $q$v Magdeburgu$q$),
  ($q$/nemecko/oberstaufen$q$, $q$do Oberstaufenu$q$, $q$v Oberstaufenu$q$),
  ($q$/nemecko/pasov$q$, $q$do Pasova$q$, $q$v Pasově$q$),
  ($q$/nemecko/postupim$q$, $q$do Postupimi$q$, $q$v Postupimi$q$),
  ($q$/nemecko/wernigerode$q$, $q$do Wernigerode$q$, $q$ve Wernigerode$q$),
  ($q$/nemecko/wittenberg$q$, $q$do Wittenbergu$q$, $q$ve Wittenbergu$q$),
  ($q$/nemecko/wrlitz$q$, $q$do Wörlitzu$q$, $q$ve Wörlitzu$q$),
  ($q$/nizozemsko/delft$q$, $q$do Delftu$q$, $q$v Delftu$q$),
  ($q$/nizozemsko/dordrecht$q$, $q$do Dordrechtu$q$, $q$v Dordrechtu$q$),
  ($q$/nizozemsko/leiden$q$, $q$do Leidenu$q$, $q$v Leidenu$q$),
  ($q$/nizozemsko/narodni-park-biesbosch$q$, $q$do národního parku Biesbosch$q$, $q$v národním parku Biesbosch$q$),
  ($q$/norsko/trondheim$q$, $q$do Trondheimu$q$, $q$v Trondheimu$q$),
  ($q$/novy-zeland/akaroa$q$, $q$do Akaroy$q$, $q$v Akaroe$q$),
  ($q$/novy-zeland/arthurs-pass$q$, $q$do Arthur's Pass$q$, $q$v Arthur's Pass$q$),
  ($q$/novy-zeland/fox-glacier$q$, $q$do Fox Glacier$q$, $q$ve Fox Glacier$q$),
  ($q$/novy-zeland/hokitika$q$, $q$do Hokitiky$q$, $q$v Hokitice$q$),
  ($q$/novy-zeland/jizni-ostrov$q$, $q$na Jižní ostrov$q$, $q$na Jižním ostrově$q$),
  ($q$/novy-zeland/kaikoura$q$, $q$do Kaikoury$q$, $q$v Kaikouře$q$),
  ($q$/novy-zeland/marlborough-sounds$q$, $q$do Marlborough Sounds$q$, $q$v Marlborough Sounds$q$),
  ($q$/novy-zeland/severni-ostrov$q$, $q$na Severní ostrov$q$, $q$na Severním ostrově$q$),
  ($q$/novy-zeland/severni-ostrov/narodni-park-tongariro$q$, $q$do národního parku Tongariro$q$, $q$v národním parku Tongariro$q$),
  ($q$/novy-zeland/severni-ostrov/rotorua$q$, $q$do Rotoruy$q$, $q$v Rotorue$q$),
  ($q$/novy-zeland/severni-ostrov/taranaki$q$, $q$do Taranaki$q$, $q$v Taranaki$q$),
  ($q$/novy-zeland/severni-ostrov/vesnice-whakapapa$q$, $q$do vesnice Whakapapa$q$, $q$ve vesnici Whakapapa$q$),
  ($q$/novy-zeland/wanaka$q$, $q$do Wanaky$q$, $q$ve Wanace$q$),
  ($q$/paraguay/asuncion$q$, $q$do Asunciónu$q$, $q$v Asunciónu$q$),
  ($q$/paraguay/ciudad-del-este$q$, $q$do Ciudad del Este$q$, $q$v Ciudad del Este$q$),
  ($q$/paraguay/filadelfia$q$, $q$do Filadelfie$q$, $q$ve Filadelfii$q$),
  ($q$/paraguay/loma-plata$q$, $q$do Loma Platy$q$, $q$v Loma Platě$q$),
  ($q$/paraguay/villarrica$q$, $q$do Villarriky$q$, $q$ve Villarrice$q$),
  ($q$/peru/aguas-calientes$q$, $q$do Aguas Calientes$q$, $q$v Aguas Calientes$q$),
  ($q$/peru/chinchero$q$, $q$do Chinchera$q$, $q$v Chincheru$q$),
  ($q$/peru/chivay$q$, $q$do Chivay$q$, $q$v Chivay$q$),
  ($q$/peru/cusco-a-posvatne-udoli$q$, $q$do Cusca a Posvátného údolí$q$, $q$v Cuscu a Posvátném údolí$q$),
  ($q$/peru/ica$q$, $q$do Icy$q$, $q$v Ice$q$),
  ($q$/peru/ica-a-nazca$q$, $q$do Icy a Nazcy$q$, $q$v Ice a Nazce$q$),
  ($q$/peru/jezero-titicaca$q$, $q$k jezeru Titicaca$q$, $q$u jezera Titicaca$q$),
  ($q$/peru/kanon-colca$q$, $q$do kaňonu Colca$q$, $q$v kaňonu Colca$q$),
  ($q$/peru/kanon-cotahuasi$q$, $q$do kaňonu Cotahuasi$q$, $q$v kaňonu Cotahuasi$q$),
  ($q$/peru/mesto-nazca$q$, $q$do města Nazca$q$, $q$ve městě Nazca$q$),
  ($q$/peru/ollantaytambo$q$, $q$do Ollantaytamba$q$, $q$v Ollantaytambu$q$),
  ($q$/peru/paracas$q$, $q$do Paracasu$q$, $q$v Paracasu$q$),
  ($q$/peru/pisac$q$, $q$do Pisacu$q$, $q$v Pisacu$q$),
  ($q$/peru/pisco$q$, $q$do Pisca$q$, $q$v Piscu$q$),
  ($q$/peru/puno$q$, $q$do Puna$q$, $q$v Punu$q$),
  ($q$/peru/puno-a-titicaca$q$, $q$do Puna a k jezeru Titicaca$q$, $q$v Punu a u jezera Titicaca$q$),
  ($q$/peru/region-arequipa$q$, $q$do regionu Arequipa$q$, $q$v regionu Arequipa$q$),
  ($q$/peru/region-lima$q$, $q$do regionu Lima$q$, $q$v regionu Lima$q$),
  ($q$/polsko/biaka-tatrzaska$q$, $q$do Białky Tatrzańské$q$, $q$v Białce Tatrzańské$q$),
  ($q$/polsko/bielsko-biala$q$, $q$do Bielska-Bialé$q$, $q$v Bielsku-Bialé$q$),
  ($q$/polsko/frombork$q$, $q$do Fromborku$q$, $q$ve Fromborku$q$),
  ($q$/polsko/gizycko$q$, $q$do Gižycka$q$, $q$v Gižycku$q$),
  ($q$/polsko/hel$q$, $q$do Helu$q$, $q$v Helu$q$),
  ($q$/polsko/kazimierz-dolny$q$, $q$do Kazimierze Dolného$q$, $q$v Kazimierzi Dolném$q$),
  ($q$/polsko/ketrzyn$q$, $q$do Ketrzynu$q$, $q$v Ketrzynu$q$),
  ($q$/polsko/kielce$q$, $q$do Kielc$q$, $q$v Kielcích$q$),
  ($q$/polsko/krosno$q$, $q$do Krosna$q$, $q$v Krosně$q$),
  ($q$/polsko/kudowa-zdroj$q$, $q$do Kudowy Zdrój$q$, $q$v Kudowě Zdrój$q$),
  ($q$/polsko/lesno$q$, $q$do Lešna$q$, $q$v Lešně$q$),
  ($q$/polsko/lodz$q$, $q$do Lodže$q$, $q$v Lodži$q$),
  ($q$/polsko/lublin$q$, $q$do Lublinu$q$, $q$v Lublinu$q$),
  ($q$/polsko/mazurska-jezera$q$, $q$na Mazurská jezera$q$, $q$na Mazurských jezerech$q$),
  ($q$/polsko/naleczow$q$, $q$do Naleczówa$q$, $q$v Naleczówě$q$),
  ($q$/polsko/niedzica$q$, $q$do Niedzice$q$, $q$v Niedzici$q$),
  ($q$/polsko/plock$q$, $q$do Plocku$q$, $q$v Plocku$q$),
  ($q$/polsko/poznan$q$, $q$do Poznaně$q$, $q$v Poznani$q$),
  ($q$/polsko/premysl$q$, $q$do Přemyšlu$q$, $q$v Přemyšlu$q$),
  ($q$/polsko/resov$q$, $q$do Řešova$q$, $q$v Řešově$q$),
  ($q$/polsko/sandomer$q$, $q$do Sandoměře$q$, $q$v Sandoměři$q$),
  ($q$/polsko/stargrad$q$, $q$do Stargradu$q$, $q$ve Stargradu$q$),
  ($q$/polsko/stetin$q$, $q$do Štětína$q$, $q$ve Štětíně$q$),
  ($q$/polsko/torun$q$, $q$do Toruně$q$, $q$v Toruni$q$),
  ($q$/polsko/wroclaw$q$, $q$do Wroclawi$q$, $q$ve Wroclawi$q$),
  ($q$/polsko/ywiec$q$, $q$do Żywce$q$, $q$v Żywci$q$),
  ($q$/polsko/zakopane$q$, $q$do Zakopaného$q$, $q$v Zakopaném$q$),
  ($q$/portugalsko/bragana$q$, $q$do Bragançy$q$, $q$v Bragançe$q$),
  ($q$/portugalsko/coimbra$q$, $q$do Coimbry$q$, $q$v Coimbře$q$),
  ($q$/portugalsko/guimares$q$, $q$do Guimarães$q$, $q$v Guimarães$q$),
  ($q$/portugalsko/madeira/calheta$q$, $q$do Calhety$q$, $q$v Calhetě$q$),
  ($q$/portugalsko/madeira/funchal$q$, $q$do Funchalu$q$, $q$ve Funchalu$q$),
  ($q$/portugalsko/madeira/paul-do-mar$q$, $q$do Paul do Mar$q$, $q$v Paul do Mar$q$),
  ($q$/portugalsko/madeira/porto-moniz$q$, $q$do Porto Moniz$q$, $q$v Porto Moniz$q$),
  ($q$/rakousko/bad-gastein$q$, $q$do Bad Gasteinu$q$, $q$v Bad Gasteinu$q$),
  ($q$/rakousko/bad-ischl$q$, $q$do Bad Ischlu$q$, $q$v Bad Ischlu$q$),
  ($q$/rakousko/graz$q$, $q$do Grazu$q$, $q$v Grazu$q$),
  ($q$/rakousko/grossglockner-hochalpenstrasse$q$, $q$na Grossglockner Hochalpenstrasse$q$, $q$na Grossglockner Hochalpenstrasse$q$),
  ($q$/rakousko/hallstatt$q$, $q$do Hallstattu$q$, $q$v Hallstattu$q$),
  ($q$/rakousko/kitzbhel$q$, $q$do Kitzbühelu$q$, $q$v Kitzbühelu$q$),
  ($q$/rakousko/linz$q$, $q$do Lince$q$, $q$v Linci$q$),
  ($q$/rakousko/pohori-dachstein$q$, $q$do pohoří Dachstein$q$, $q$v pohoří Dachstein$q$),
  ($q$/rakousko/zell-am-see$q$, $q$do Zell am See$q$, $q$v Zell am See$q$),
  ($q$/recko/epirus-region$q$, $q$do Epiru$q$, $q$v Epiru$q$),
  ($q$/recko/korfu/benitses$q$, $q$do Benitses$q$, $q$v Benitses$q$),
  ($q$/recko/korfu/kassiopi$q$, $q$do Kassiopi$q$, $q$v Kassiopi$q$),
  ($q$/recko/korfu/mesto-korfu$q$, $q$do města Korfu$q$, $q$ve městě Korfu$q$),
  ($q$/recko/korfu/ostruvek-vidos$q$, $q$na ostrůvek Vidos$q$, $q$na ostrůvku Vidos$q$),
  ($q$/recko/korfu/paleokastritsa$q$, $q$do Paleokastrítsy$q$, $q$v Paleokastrítse$q$),
  ($q$/recko/korfu/palia-perithia$q$, $q$do Palia Perithia$q$, $q$v Palia Perithia$q$),
  ($q$/recko/kos/kardamena$q$, $q$do Kardameny$q$, $q$v Kardameně$q$),
  ($q$/recko/kos/kefalos$q$, $q$do Kefalosu$q$, $q$v Kefalosu$q$),
  ($q$/recko/kos/mastihari$q$, $q$do Mastihari$q$, $q$v Mastihari$q$),
  ($q$/recko/kos/mesto-kos$q$, $q$do města Kos$q$, $q$ve městě Kos$q$),
  ($q$/recko/kreta/agia-deka$q$, $q$do Agia Deka$q$, $q$v Agia Deka$q$),
  ($q$/recko/kreta/agia-marina$q$, $q$do Agia Mariny$q$, $q$v Agia Marině$q$),
  ($q$/recko/kreta/agios-nikolaos$q$, $q$do Agios Nikolaos$q$, $q$v Agios Nikolaos$q$),
  ($q$/recko/kreta/chania$q$, $q$do Chanie$q$, $q$v Chanii$q$),
  ($q$/recko/kreta/heraklion$q$, $q$do Heraklionu$q$, $q$v Heraklionu$q$),
  ($q$/recko/kreta/matala$q$, $q$do Mataly$q$, $q$v Matale$q$),
  ($q$/recko/kreta/paleochora$q$, $q$do Paleochory$q$, $q$v Paleochoře$q$),
  ($q$/recko/kreta/rethymno$q$, $q$do Rethymna$q$, $q$v Rethymnu$q$),
  ($q$/recko/lefkada/lefkas$q$, $q$do Lefkasu$q$, $q$v Lefkasu$q$),
  ($q$/recko/lefkada/nidri$q$, $q$do Nidri$q$, $q$v Nidri$q$),
  ($q$/recko/lefkada/sivota$q$, $q$do Sivoty$q$, $q$v Sivotě$q$),
  ($q$/recko/lefkada/vassiliki$q$, $q$do Vassiliki$q$, $q$ve Vassiliki$q$),
  ($q$/recko/lesbos/agiasos$q$, $q$do Agiasosu$q$, $q$v Agiasosu$q$),
  ($q$/recko/lesbos/molyvos-mithymna$q$, $q$do Molyvosu$q$, $q$v Molyvosu$q$),
  ($q$/recko/lesbos/mytilena$q$, $q$do Mytileny$q$, $q$v Mytileně$q$),
  ($q$/recko/lesbos/petra$q$, $q$do Petry$q$, $q$v Petře$q$),
  ($q$/recko/lesbos/sigri$q$, $q$do Sigri$q$, $q$v Sigri$q$),
  ($q$/recko/lesbos/skala-eresou$q$, $q$do Skala Eresou$q$, $q$ve Skala Eresou$q$),
  ($q$/recko/parga$q$, $q$do Pargy$q$, $q$v Parze$q$),
  ($q$/recko/rhodos/ialyssos$q$, $q$do Ialyssosu$q$, $q$v Ialyssosu$q$),
  ($q$/recko/rhodos/kameiros$q$, $q$do Kameirosu$q$, $q$v Kameirosu$q$),
  ($q$/recko/rhodos/lindos$q$, $q$do Lindosu$q$, $q$v Lindosu$q$),
  ($q$/recko/rhodos/mesto-rhodos$q$, $q$do města Rhodos$q$, $q$ve městě Rhodos$q$),
  ($q$/recko/santorini/akrotiri$q$, $q$do Akrotiri$q$, $q$v Akrotiri$q$),
  ($q$/recko/santorini/fira$q$, $q$do Firy$q$, $q$ve Fiře$q$),
  ($q$/recko/santorini/oia$q$, $q$do Oie$q$, $q$v Oii$q$),
  ($q$/recko/solun$q$, $q$do Soluně$q$, $q$v Soluni$q$),
  ($q$/recko/zakynthos/laganas$q$, $q$do Laganasu$q$, $q$v Laganasu$q$),
  ($q$/recko/zakynthos/zakinthos$q$, $q$do Zakinthosu$q$, $q$v Zakinthosu$q$),
  ($q$/rumunsko/alba-iulia$q$, $q$do Alba Iulie$q$, $q$v Alba Iulii$q$),
  ($q$/rumunsko/delta-dunaje$q$, $q$do delty Dunaje$q$, $q$v deltě Dunaje$q$),
  ($q$/rumunsko/jasy$q$, $q$do Jas$q$, $q$v Jasech$q$),
  ($q$/rumunsko/klastery-jizni-bukoviny$q$, $q$do Jižní Bukoviny$q$, $q$v Jižní Bukovině$q$),
  ($q$/rumunsko/konstance$q$, $q$do Konstance$q$, $q$v Konstanci$q$),
  ($q$/rumunsko/maramures$q$, $q$do Maramureše$q$, $q$v Maramureši$q$),
  ($q$/rumunsko/rumunska-cast-moldavie$q$, $q$do rumunské části Moldávie$q$, $q$v rumunské části Moldávie$q$),
  ($q$/rumunsko/sibiu$q$, $q$do Sibiu$q$, $q$v Sibiu$q$),
  ($q$/rumunsko/sighioara$q$, $q$do Sighişoary$q$, $q$v Sighişoaře$q$),
  ($q$/rumunsko/sinaia$q$, $q$do Sinaie$q$, $q$v Sinaii$q$),
  ($q$/rumunsko/targoviste$q$, $q$do Targoviste$q$, $q$v Targoviste$q$),
  ($q$/rumunsko/temesvar$q$, $q$do Temešváru$q$, $q$v Temešváru$q$),
  ($q$/rumunsko/transylvanie$q$, $q$do Transylvánie$q$, $q$v Transylvánii$q$),
  ($q$/rumunsko/valassko$q$, $q$do Valašska$q$, $q$ve Valašsku$q$),
  ($q$/rusko/jekaterinburg$q$, $q$do Jekatěrinburgu$q$, $q$v Jekatěrinburgu$q$),
  ($q$/rusko/karelie$q$, $q$do Karélie$q$, $q$v Karélii$q$),
  ($q$/rusko/kazan$q$, $q$do Kazaně$q$, $q$v Kazani$q$),
  ($q$/rusko/kizi$q$, $q$na Kiži$q$, $q$na Kiži$q$),
  ($q$/rusko/niznij-novgorod$q$, $q$do Nižního Novgorodu$q$, $q$v Nižním Novgorodu$q$),
  ($q$/rusko/novosibirsk$q$, $q$do Novosibirsku$q$, $q$v Novosibirsku$q$),
  ($q$/rusko/omsk$q$, $q$do Omsku$q$, $q$v Omsku$q$),
  ($q$/rusko/petrozavodsk$q$, $q$do Petrozavodsku$q$, $q$v Petrozavodsku$q$),
  ($q$/severni-irsko/armagh$q$, $q$do Armaghu$q$, $q$v Armaghu$q$),
  ($q$/severni-irsko/derry$q$, $q$do Derry$q$, $q$v Derry$q$),
  ($q$/severni-irsko/lisburn$q$, $q$do Lisburnu$q$, $q$v Lisburnu$q$),
  ($q$/severni-irsko/newry$q$, $q$do Newry$q$, $q$v Newry$q$),
  ($q$/skotsko/aberdeen$q$, $q$do Aberdeenu$q$, $q$v Aberdeenu$q$),
  ($q$/skotsko/balloch$q$, $q$do Ballochu$q$, $q$v Ballochu$q$),
  ($q$/skotsko/dundee$q$, $q$do Dundee$q$, $q$v Dundee$q$),
  ($q$/skotsko/fort-william$q$, $q$do Fort Williamu$q$, $q$ve Fort Williamu$q$),
  ($q$/skotsko/narodni-park-loch-lomond-a-trossachs$q$, $q$do národního parku Loch Lomond a Trossachs$q$, $q$v národním parku Loch Lomond a Trossachs$q$),
  ($q$/skotsko/perth$q$, $q$do Perthu$q$, $q$v Perthu$q$),
  ($q$/skotsko/perthshire$q$, $q$do Perthshire$q$, $q$v Perthshire$q$),
  ($q$/skotsko/stirling$q$, $q$do Stirlingu$q$, $q$ve Stirlingu$q$),
  ($q$/skotsko/the-great-glen$q$, $q$do Great Glenu$q$, $q$v Great Glenu$q$),
  ($q$/slovensko/banska-stiavnica$q$, $q$do Banské Štiavnice$q$, $q$v Banské Štiavnici$q$),
  ($q$/slovensko/besenova$q$, $q$do Bešeňové$q$, $q$v Bešeňové$q$),
  ($q$/slovensko/bojnice$q$, $q$do Bojnic$q$, $q$v Bojnicích$q$),
  ($q$/slovensko/cerveny-klastor$q$, $q$do Červeného Kláštora$q$, $q$v Červeném Kláštoru$q$),
  ($q$/slovensko/demnovska-dolina$q$, $q$do Demänovské doliny$q$, $q$v Demänovské dolině$q$),
  ($q$/slovensko/komarno$q$, $q$do Komárna$q$, $q$v Komárně$q$),
  ($q$/slovensko/levice$q$, $q$do Levic$q$, $q$v Levicích$q$),
  ($q$/slovensko/levoca$q$, $q$do Levoče$q$, $q$v Levoči$q$),
  ($q$/slovensko/marianka$q$, $q$do Marianky$q$, $q$v Mariance$q$),
  ($q$/slovensko/nitra$q$, $q$do Nitry$q$, $q$v Nitře$q$),
  ($q$/slovensko/piestany$q$, $q$do Piešťan$q$, $q$v Piešťanech$q$),
  ($q$/slovensko/rajecke-teplice$q$, $q$do Rajeckých Teplic$q$, $q$v Rajeckých Teplicích$q$),
  ($q$/slovensko/skalica$q$, $q$do Skalice$q$, $q$ve Skalici$q$),
  ($q$/slovensko/spisska-nova-ves$q$, $q$do Spišské Nové Vsi$q$, $q$ve Spišské Nové Vsi$q$),
  ($q$/slovensko/spisske-podhradi$q$, $q$do Spišského podhradí$q$, $q$ve Spišském podhradí$q$),
  ($q$/slovensko/sturovo$q$, $q$do Štúrova$q$, $q$ve Štúrově$q$),
  ($q$/slovensko/terchova$q$, $q$do Terchové$q$, $q$v Terchové$q$),
  ($q$/slovinsko/bled$q$, $q$do Bledu$q$, $q$v Bledu$q$),
  ($q$/slovinsko/bohinj$q$, $q$do Bohinje$q$, $q$v Bohinji$q$),
  ($q$/slovinsko/bovec$q$, $q$do Bovce$q$, $q$v Bovci$q$),
  ($q$/slovinsko/brezice$q$, $q$do Brežic$q$, $q$v Brežicích$q$),
  ($q$/slovinsko/celje$q$, $q$do Celje$q$, $q$v Celji$q$),
  ($q$/slovinsko/izola$q$, $q$do Izoly$q$, $q$v Izole$q$),
  ($q$/slovinsko/lasko$q$, $q$do Laška$q$, $q$v Lašku$q$),
  ($q$/slovinsko/piran$q$, $q$do Piranu$q$, $q$v Piranu$q$),
  ($q$/slovinsko/portoroz$q$, $q$do Portorože$q$, $q$v Portoroži$q$),
  ($q$/slovinsko/ptuj$q$, $q$do Ptuje$q$, $q$v Ptuji$q$),
  ($q$/spanelsko/gran-canaria$q$, $q$na Gran Canarii$q$, $q$na Gran Canarii$q$),
  ($q$/spanelsko/kanarske-ostrovy$q$, $q$na Kanárské ostrovy$q$, $q$na Kanárských ostrovech$q$),
  ($q$/spanelsko/san-sebastian$q$, $q$do San Sebastiánu$q$, $q$v San Sebastiánu$q$),
  ($q$/srbsko/cesko-selo$q$, $q$do Češkého sela$q$, $q$v Češkém selu$q$),
  ($q$/srbsko/stari-ras$q$, $q$do Stari Rasu$q$, $q$ve Stari Rasu$q$),
  ($q$/srbsko/topola$q$, $q$do Topoly$q$, $q$v Topole$q$),
  ($q$/srbsko/zlatibor$q$, $q$na Zlatibor$q$, $q$na Zlatiboru$q$),
  ($q$/sri-lanka/anuradhapura$q$, $q$do Anurádhapury$q$, $q$v Anurádhapuře$q$),
  ($q$/sri-lanka/centralni-provincie$q$, $q$do Centrální provincie$q$, $q$v Centrální provincii$q$),
  ($q$/sri-lanka/hambantota$q$, $q$do Hambantoty$q$, $q$v Hambantotě$q$),
  ($q$/sri-lanka/mirissa$q$, $q$do Mirissy$q$, $q$v Mirisse$q$),
  ($q$/sri-lanka/negombo$q$, $q$do Negomba$q$, $q$v Negombu$q$),
  ($q$/sri-lanka/polonnaruwa$q$, $q$do Polonnaruwy$q$, $q$v Polonnaruwě$q$),
  ($q$/svedsko/abisko$q$, $q$do Abiska$q$, $q$v Abisku$q$),
  ($q$/svedsko/kiruna$q$, $q$do Kiruny$q$, $q$v Kiruně$q$),
  ($q$/svedsko/sigtuna$q$, $q$do Sigtuny$q$, $q$v Sigtuně$q$),
  ($q$/svycarsko/lausanne$q$, $q$do Lausanne$q$, $q$v Lausanne$q$),
  ($q$/thajsko/bangkok$q$, $q$do Bangkoku$q$, $q$v Bangkoku$q$),
  ($q$/thajsko/chiang-mai$q$, $q$do Chiang Mai$q$, $q$v Chiang Mai$q$),
  ($q$/thajsko/doi-inthanon-national-park$q$, $q$do národního parku Doi Inthanon$q$, $q$v národním parku Doi Inthanon$q$),
  ($q$/thajsko/koh-chang$q$, $q$na Koh Chang$q$, $q$na Koh Changu$q$),
  ($q$/thajsko/krabi$q$, $q$do Krabi$q$, $q$v Krabi$q$),
  ($q$/thajsko/phuket$q$, $q$na Phuket$q$, $q$na Phuketu$q$),
  ($q$/tunisko/djerba$q$, $q$na Djerbu$q$, $q$na Djerbě$q$),
  ($q$/tunisko/sousse$q$, $q$do Sousse$q$, $q$v Sousse$q$),
  ($q$/tunisko/tunis$q$, $q$do Tunisu$q$, $q$v Tunisu$q$),
  ($q$/turecko/kappadokie$q$, $q$do Kappadokie$q$, $q$v Kappadokii$q$),
  ($q$/ukrajina/odesa$q$, $q$do Oděsy$q$, $q$v Oděse$q$),
  ($q$/usa/anchorage$q$, $q$do Anchorage$q$, $q$v Anchorage$q$),
  ($q$/usa/arizona$q$, $q$do Arizony$q$, $q$v Arizoně$q$),
  ($q$/usa/cheyenne$q$, $q$do Cheyenne$q$, $q$v Cheyenne$q$),
  ($q$/usa/cody$q$, $q$do Cody$q$, $q$v Cody$q$),
  ($q$/usa/denali-national-park$q$, $q$do národního parku Denali$q$, $q$v národním parku Denali$q$),
  ($q$/usa/fairbanks$q$, $q$do Fairbanksu$q$, $q$ve Fairbanksu$q$),
  ($q$/usa/grand-canyon$q$, $q$do Grand Canyonu$q$, $q$v Grand Canyonu$q$),
  ($q$/usa/grand-canyon/north-rim$q$, $q$na North Rim$q$, $q$na North Rimu$q$),
  ($q$/usa/grand-canyon/south-rim$q$, $q$na South Rim$q$, $q$na South Rimu$q$),
  ($q$/usa/homer$q$, $q$do Homeru$q$, $q$v Homeru$q$),
  ($q$/usa/jackson$q$, $q$do Jacksonu$q$, $q$v Jacksonu$q$),
  ($q$/usa/juneau$q$, $q$do Juneau$q$, $q$v Juneau$q$),
  ($q$/usa/narodni-park-death-valley$q$, $q$do národního parku Death Valley$q$, $q$v národním parku Death Valley$q$),
  ($q$/usa/odlehle-oblasti$q$, $q$do odlehlých oblastí$q$, $q$v odlehlých oblastech$q$),
  ($q$/usa/seward$q$, $q$do Sewardu$q$, $q$v Sewardu$q$),
  ($q$/usa/shoshone-national-forest$q$, $q$do národního lesa Shoshone$q$, $q$v národním lese Shoshone$q$),
  ($q$/usa/valdez$q$, $q$do Valdezu$q$, $q$ve Valdezu$q$),
  ($q$/vietnam/da-nang$q$, $q$do Da Nangu$q$, $q$v Da Nangu$q$),
  ($q$/vietnam/ho-ci-minovo-mesto$q$, $q$do Ho Či Minova Města$q$, $q$v Ho Či Minově Městě$q$),
  ($q$/vietnam/hoi-an$q$, $q$do Hoi Anu$q$, $q$v Hoi Anu$q$),
  ($q$/wales/conwy$q$, $q$do Conwy$q$, $q$v Conwy$q$),
  ($q$/wales/pembrokeshire$q$, $q$do Pembrokeshire$q$, $q$v Pembrokeshire$q$),
  ($q$/wales/swansea$q$, $q$do Swansea$q$, $q$ve Swansea$q$),
  ($q$/wales/tintern$q$, $q$do Tinternu$q$, $q$v Tinternu$q$),
  ($q$/peru/machu-picchu$q$, $q$do Machu Picchu$q$, $q$v Machu Picchu$q$);

CREATE TABLE IF NOT EXISTS zaloha.pages_pady_2026_09_04 AS
  SELECT p.id, p.full_slug, p.detail_genitive, p.detail_locative, now() AS zalohovano FROM pages p WHERE false;
INSERT INTO zaloha.pages_pady_2026_09_04 (id, full_slug, detail_genitive, detail_locative, zalohovano)
  SELECT p.id, p.full_slug, p.detail_genitive, p.detail_locative, now()
  FROM pages p JOIN pady ON pady.slug = p.full_slug
  WHERE p.category = 'Místo k navštívení'
    AND (COALESCE(p.detail_genitive, '') = '' OR COALESCE(p.detail_locative, '') = '');

UPDATE pages p SET
  detail_genitive = CASE WHEN COALESCE(p.detail_genitive, '') = '' THEN pady.gen ELSE p.detail_genitive END,
  detail_locative = CASE WHEN COALESCE(p.detail_locative, '') = '' THEN pady.loc ELSE p.detail_locative END
FROM pady WHERE pady.slug = p.full_slug AND p.category = 'Místo k navštívení'
  AND (COALESCE(p.detail_genitive, '') = '' OR COALESCE(p.detail_locative, '') = '');

UPDATE _pages_v v SET
  version_detail_genitive = CASE WHEN COALESCE(v.version_detail_genitive, '') = '' THEN pady.gen ELSE v.version_detail_genitive END,
  version_detail_locative = CASE WHEN COALESCE(v.version_detail_locative, '') = '' THEN pady.loc ELSE v.version_detail_locative END
FROM pady JOIN pages p ON p.full_slug = pady.slug
WHERE v.parent_id = p.id AND v.latest
  AND (COALESCE(v.version_detail_genitive, '') = '' OR COALESCE(v.version_detail_locative, '') = '');

SELECT count(*) AS "míst stále bez pádu" FROM pages
  WHERE _status = 'published' AND category = 'Místo k navštívení'
  AND (COALESCE(detail_genitive, '') = '' OR COALESCE(detail_locative, '') = '');
COMMIT;
